### PR TITLE
Alpha

### PR DESCRIPTION
**Pull request by TD-D**
I was worried that working on two machines might create this problem, despite having recloned my repository today on my work machine.  Should just be the Mar 22, 2013 commit...

### CODE REVIEW

**Comment by Merp** [comment]
Are you encountering an error when you try to run git rebase merp/Alpha? I've tested this on my local using tracking branches and don't get any errors. You will however run into an error if you don't check the force option when you push.

Also, the last two commits list unknown author. Looks like the work machine doesn't have a name/email set up in the options (git config --global user.name and user.email).

Working on two different machines just requires you to always commit/push work after its done as you should, and running git fetch origin + git merge --ff-only origin/Alpha before making changes/commits. If this command fails, it means you've got some extra commits in there somewhere, so it is necessary to run git rebase origin/Alpha

**Comment by TD-D** [comment]
Did I get it right this time?  What I don't understand is why after rebasing, I get everybody else's commit as part of my pull request?

**Comment by TD-D** [comment]
Overrun fueling for EP5G601B on the above commit, but RR template will now allow me to use the scripts to add these to all the new definitions.

**Comment by Merp** [comment]
It looks as though you rebased my branch onto yours instead of the opposite. In the network view you can see your Alpha is detached from mine starting March 7. After rebasing your branch onto mine, it would not detach from mine until the head on March 20 (or whenever you last fetched), as that is the 'base' you are re-basing onto.

I just tested it again using a tracking branch of your latest Alpha (with everyone else's commits), and rebasing it onto merp/Alpha cleaned it all up. The exact commands (from your perspective) to repeat the test I just did are: 

  git fetch merp
  git checkout Alpha
  git rebase merp/Alpha

 If this doesn't work out, I'll clean it up tomorrow, pull it all in, and post the commands needed to bring your repos up to date with that.

**Comment by TD-D** [comment]
Ok, just did that, looks like it worked. Sorry for being so dense with this, I think I need to go back to the material and reread.  This is the message I got:

Oz@OZ-PC /g/dev/Subarudefs (Alpha)
$ git fetch Merp

Oz@OZ-PC /g/dev/Subarudefs (Alpha)
$ git checkout Alpha
Already on 'Alpha'

Oz@OZ-PC /g/dev/Subarudefs (Alpha)
$ git rebase merp/Alpha
First, rewinding head to replay your work on top of it...
Applying: RR AZ1G700K definition 2012 EDM WRX STI
Applying: Ecuflash AZ1G700K definition 2012 EDM WRX STI
Applying: Update RR_AZ1G700K.xml
Applying: RR EP5G601B definition 2012 Impreza 2.0i CVT
Applying: Ecuflash definition EP5G601B / 2012 Impreza 2.0i CVT
Applying: Edits to requested torque tables
Applying: Added Overrun Fueling to both RR and Ecuflash

Oz@OZ-PC /g/dev/Subarudefs (Alpha)
$

**Comment by Merp** [comment]
That looks good, same output as my test. :+1:  Go ahead and push it up and I'll get it pulled in.

**Comment by TD-D** [comment]
Will do - did that on the home machine, so will push it tonight.

**Comment by TD-D** [comment]
Ok - all good now?  I landed up also having to do a git pull, due to this message:

Pushing to https://github.com/TD-D/SubaruDefs
To https://github.com/TD-D/SubaruDefs
 ! [rejected]        Alpha -> Alpha (non-fast-forward)
error: failed to push some refs to 'https://github.com/TD-D/SubaruDefs'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by Merp** [comment]
For a rebase workflow, we never use git pull which is essentially git fetch + git merge. Only git merge --ff-only or rebase is used. The reason the push was rejected was because the rebase reordered and removed some of the commits, which causes rejection. The solution is to force push after a rebase. To rectify this, you can use:

```
  git reset --mixed 580ae7817914
```

This will reset your branch to the state just before the merge (caused by pull). From there, push with the force option and we're all set.

**Comment by TD-D** [comment]
Ok, just did that, seems to have worked:

Pushing to https://github.com/TD-D/SubaruDefs
POST git-receive-pack (173 bytes)
To https://github.com/TD-D/SubaruDefs
- 12c8380...580ae78 Alpha -> Alpha (forced update)
  updating local tracking ref 'refs/remotes/origin/Alpha'

**Pull request merged**
