### PR TITLE
Alpha

### PR DESCRIPTION
**Pull request by TD-D**
AE5M100G edits - apologies for the multiple commits, picked the errors up incrementally as the user reported them.

### CODE REVIEW

**Comment by Merp** [comment]
No worries about multiple commits,but lets get your branch back in sync. 

Because I had pushed another commit prior to yours, our Alpha branches got out of sync. https://github.com/Merp/SubaruDefs/network will show whats going on. 

Now, to get Alpha back in sync:

```
 git checkout Alpha
 git fetch --all
 git rebase merp/Alpha
 git push origin Alpha
```

 To avoid this in the future, do the following before working on new commits.

```
 git checkout Alpha (switches to local Alpha branch)
 git fetch --all (fetches everything from remotes)
 git merge --ff-only merp/Alpha (brings your local Alpha up to date with my repo)
```

Or in GUI:

```
 Branch->Create->Match tracking, fast forward only, fetch tracking branch, select merp/Alpha
```

If something slips through, no problem, just run 'git rebase merp/Alpha' and push. That's how I pulled your last changes in, it basically takes your current branch's new commits and reapplies them on top of / after the commits in the target (merp/Alpha).

**Comment by TD-D** [comment]
Hmm.. odd - I did exactly that on this last set of commit - made sure I
fetched all, and then Create with fast forward only. Did it not sync?

**Comment by Merp** [comment]
Its possible that the time we were working on them overlapped or I didn't push mine up immediately. Apologies if that was the case. No problem though, the rebase will take care of it.

After the rebase, refreshing the network view should show your latest 3 commits as starting from the tip of my Alpha branch.

**Comment by TD-D** [comment]
Cool, well - getting the hang of it, slowly :)

I'm wondering if there isn't the potential for logger addresses - at the
moment it's manually posted and incorporated via Dale. I know there was a
debate about it...

I really need to reformulate the Alpha definitions (the stuff I dug out)
into Romraider def format - then the scripts will spit them out as well,
and all new definitions I post will automatically have the new stuff in
them.  It's just too tedious to do it manually.

**Comment by Merp** [comment]
I've got some code written in SharpTune that can add to the latest logger from Dale, including params that don't exist there. However, its only working for patch production right now and needs some adapting to accept different input formats. Since the editor defs aren't much use without the loggers, I'll put this at the top of my todo.

Regarding the new Alpha defs, that is probably your best bet. The timeframe for deprecating RR ecu defs format (in favor of ECUFlash style) is up in the air right now... I coded somewhere around half of it before getting distracted, and don't plan to revisit it until I have git and yaml working in RR (mostly functional test branch is in my repo). However, once that is done I have code that can automatically populate ECUFlash definitions from a base.

**Comment by TD-D** [comment]
Hey Merp - I seem to still have an open commit from when the branches went out of sync - any way to close it?  In any case, new commit for AZ1G700K.

**Comment by Merp** [comment]
Sure, commit all changes in your Alpha branch, then fetch all, then rebase onto merp/Alpha. (command line: git status (make sure no staged/unstaged changes left), git fetch --all, git rebase merp/Alpha.

**Comment by Merp** [comment]
Then push and open another request.

**Pull request closed without merging**
