### PR TITLE
Alpha

### PR DESCRIPTION
**Pull request by TD-D**
RR_AE5IB40L definition,

### CODE REVIEW

**Comment by Merp** [comment]
Please rebase onto my Alpha and remove those first two commits. 

```
 git checkout Alpha
 git fetch merp
 git rebase -i merp/Alpha
```

Then delete the lines for the first two commits 1e51259 and 4cf1227, that definition is already in my repo from when you squashed those commits. Must have been on your other machine?

**Comment by TD-D** [comment]
Yup... it seems to have brought them back in after the previous squash.

Ok - done, seems to have removed those two commits.

Cheers,
Oren

**Comment by Merp** [comment]
Not seeing it yet, keep in mind that rebase will require push --force if it shuffles any commits around.

To get your other machine up to date after a rebase like this will require a reset to origin/Alpha. StackOverflow has a good writeup on the differences between soft/mixed/hard resets.

**Comment by TD-D** [comment]
OK - pushed it, check now.

**Comment by Merp** [comment]
Excellent work, thanks!

**Pull request merged**
