### PR TITLE
Alpha

### PR DESCRIPTION
**Pull request by TD-D**

### CODE REVIEW

**Comment by Merp** [comment]
Please rebase onto my latest Alpha and I'll pull it in. Might as well squash these three commits into one while you're at it.

**Comment by TD-D** [comment]
Ok, I think that's done it. Did you reversion your Alpha branch? I had a
hell of time pushing today...

**Comment by Merp** [comment]
I added a few commits that others had pushed a while back. Squash looks good but I'm still showing your commits as based off an old Alpha. Make sure you fetch my latest before rebasing. Network view is really handy for visualizing this: https://github.com/Merp/SubaruDefs/network

**Comment by TD-D** [comment]
Now?

**Comment by Merp** [comment]
Hmm, still based off a June 11th commit, but has all the subsequent commits in it.

git checkout Alpha
git fetch --all
git rebase Merp/Alpha

Should do the trick, worked over here.

**Comment by TD-D** [comment]
Odd - that's exactly what I was doing on my work machine - rebased, but it
based off the old commit. Did it at home now - and worked perfectly.  This
working off two machines is a pain in the ass...

**Comment by Merp** [comment]
That's odd. The key to working on multiple machines is to always push work before switching, and always fetch + fast forward when you get to the other machine.

If the rebase doesn't work right on the other machine let me know and I will pull this commit in manually and then you can just reset to mine.

**Comment by TD-D** [comment]
Hey Merril - can I ask you a favour to just pull in all the various
commits? I'm worried I'm going to mess something up if I rebase, there have
been so many.

**Comment by Merp** [comment]
I've pulled everything in, but I had to edit that merge commit as it reverted a bunch of changes in the 32BITBASE in addition to adding the BRZ stuff. So, fast forwarding won't work, meaning you'll have to reset to my Alpha branch. But first, check commit 3e42bbf306ebb7b2e147ba44b69e1c627ebc9255 and make sure I got everything that was updated in 32BITBASE.

**Comment by TD-D** [comment]
Yup - that's all of it. I'll go ahead and rebase.

How you keeping?

**Comment by Merp** [comment]
If you rebase, you will run into a merge conflict from that merge commit. 

You can run:
     git rebase -i HEAD~4
and delete the line for commit 24057ad, then rebase will work

Alternatively reset will work, but will clobber anything that isn't in my Alpha branch.
    git reset --hard Merp/Alpha

I've been better, but can't really complain :) Hope everything is well with you.

**Comment by TD-D** [comment]
I'll delete 24057ad https://github.com/Merp/SubaruDefs/commit/24057ad -
actually just WIP, not definitions which are functioning (well, not fully
formed at least). Thanks mate.

**Comment by Merp** [comment]
No problem, the new tables will show back up after rebasing, they're in 3e42bbf306 on my branch.

**Comment by TD-D** [comment]
Ah shit, I think I've created a mess again - I'm now rebase on Merp/Alpha,
but my origin branch seems to have diverged...

**Comment by TD-D** [comment]
Ok, I think I managed to clean it up by resolving the conflicts and doing a
merge -a

When you get a chance, if you could check it out, thanks.

**Comment by Merp** [comment]
Hmm, not sure what happened there. 

If you pushed, everything looks fine, but go through those last 4 commits and make sure everything looks ok, I cleaned up a couple things and added the new CEL stuff that got clipped before.

I'm not familiar with merge -a, its best to never use merge with a rebase workflow (except with --ff-only, or --squash).

**Comment by TD-D** [comment]
Thanks - managed to push it all this morning, everything in order.

I still manage to get myself thoroughly confused with Github occasionally ;)

**Pull request merged**
