### PR TITLE
Corrected ecu ID

### PR DESCRIPTION
**Pull request by TD-D**
Minor correction to ECU id, picked up by Dale.

### CODE REVIEW

**Comment by Merp** [comment]
There's a leftover .bak file in there. Remove that file, amend the last commit with the removal, and force-push. Also, if you could throw the calid/ecuid in the commit message that would be awesome.

**Comment by Merp** [comment]
Squash the first two commits into one and optionally the last three into one or two and we're set.

**Comment by TD-D** [comment]
Ok, cleaned up, hopefully did it properly.

**Comment by TD-D** [comment]
Quick question - is the preference that I do a separate commit for each definition, or should I just commit whatever I have in one go? What's the protocol?

**Comment by Merp** [comment]
Hmm, they got squashed ok but that .bak file is still in there.

```
 git rebase -i HEAD~3 
```

Then edit the first commit and continue. Once the rebase gets there and pauses for the edit:

```
 git reset HEAD^
```

This will unstage all the changes so you can re-do that commit. Remove the .bak files, then:

```
 git add .
 git commit -m "corrected ecuid for <rom>"
 git rebase --continue
```

That should take care of it. As for commits, It doesn't really matter to me as long as there aren't a bunch of random changes spread around a single commit. More importantly, just squash any bug fixes that get found before they get pulled in.

**Comment by TD-D** [comment]
I think I've complicated things by just deleting the two *.bak file in the
middle of rebasing... not sure where to next.  I think the *.bak files
crept back in during the squash - the commit that deleted them was removed.

**Comment by Merp** [comment]
Hmm, the commit shouldn't be removed if you use squash. To clarify, when I say squash or edit while using rebase -i, I mean changing the 'pick' to that word.

From where you are now:

```
git rebase -i HEAD~4
```

Reorder the lines so that your last commit (deleting .bak) is immediately after the commit that added the .bak, and change the deleting commit's command to squash instead of pick.

**Comment by TD-D** [comment]
Ok, done it - I forgot about squash - deleted the commit (hence the
deletion of the bak files was reversed).

**Pull request merged**
