### PR TITLE
Alpha

### PR DESCRIPTION
**Pull request by TD-D**
EP5F301I definition for RR and Ecuflash (first one was the wrong definition file...)

### CODE REVIEW

**Comment by Merp** [comment]
Hop on IRC and I'll explain how to clean these up. Using rebase -i you can easily squash these into a single commit. 

   git rebase -i HEAD~2

Then change the bottom commit from 'pick' to 'squash' (you'll need to be familiar with the basics of vim to do this) and exit vim. It will then prompt you to fix up the commit message (again in vim). Exit again and it should be squashed. It will require --force when pushing.

If you're busy with other stuff just lmk and I'll pull it in and you can just reset to my Alpha.

**Comment by TD-D** [comment]
I’ll give it a bash, excuse the pun.  I’ve used vim extensively in the past in bsd when I was setting up hackintoshs and in linux, so let’s see if I can remember ;)

**Comment by TD-D** [comment]
Done, looks like it squashed the two fine.

**Comment by Merp** [comment]
Great work, thanks!

**Pull request merged**
